version: '3.3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 7000:7000
  ui:
    build:
      context: ./web
      dockerfile: ./Dockerfile
  nginx:
    image: nginx
    ports:
      - 7777:8080
    volumes:
    - ./api-nginx.conf:/etc/nginx/conf.d/api-nginx.conf



