FROM node:8

# устанавливаем простой HTTP-сервер для статики
#RUN npm install -g http-server

# делаем каталог 'app' текущим рабочим каталогом
WORKDIR /app

# копируем оба 'package.json' и 'package-lock.json' (если есть)
COPY package*.json ./

# устанавливаем зависимости проекта
RUN npm install

# копируем файлы и каталоги проекта в текущий рабочий каталог (т.е. в каталог 'app')
COPY . .

# собираем приложение для production с минификацией

EXPOSE 8080
CMD ["npm", "run", "serve"]
#CMD [ "http-server", "dist"]
